from enum import Enum


class FactoryState(str, Enum):
    """End-to-end lifecycle states of a feature moving through the factory."""

    BRD_RECEIVED = "BRD_RECEIVED"
    INTAKE = "INTAKE"
    CLARIFICATION = "CLARIFICATION"
    HUMAN_INPUT = "HUMAN_INPUT"
    REQUIREMENTS_READY = "REQUIREMENTS_READY"
    DECOMPOSED = "DECOMPOSED"
    SPECIFIED = "SPECIFIED"
    KNOWLEDGE_MINED = "KNOWLEDGE_MINED"
    DESIGNED = "DESIGNED"
    TASKS_READY = "TASKS_READY"
    TEST_DESIGNED = "TEST_DESIGNED"
    IMPLEMENTING = "IMPLEMENTING"
    BUILT = "BUILT"
    UNIT_TESTED = "UNIT_TESTED"
    DIAGNOSE = "DIAGNOSE"
    RETEST = "RETEST"
    PR_CREATED = "PR_CREATED"
    REVIEWED = "REVIEWED"
    MERGE_READY = "MERGE_READY"
    POLICY_GATE = "POLICY_GATE"
    MERGED = "MERGED"
    PACKAGED = "PACKAGED"
    PUBLISHED = "PUBLISHED"
    DEPLOYED = "DEPLOYED"
    FUNCTIONAL_TESTED = "FUNCTIONAL_TESTED"
    AC_VALIDATED = "AC_VALIDATED"
    STORY_COMPLETED = "STORY_COMPLETED"
    LEARNED = "LEARNED"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"


class TestStatus(str, Enum):
    NOT_RUN = "NOT_RUN"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class FailureClass(str, Enum):
    """Failure taxonomy; each class routes to a repair owner."""

    CODE_DEFECT = "CODE_DEFECT"
    TEST_DEFECT = "TEST_DEFECT"
    SPEC_DEFECT = "SPEC_DEFECT"
    SPEC_AMBIGUITY = "SPEC_AMBIGUITY"
    DATA_DEFECT = "DATA_DEFECT"
    ENVIRONMENT_DEFECT = "ENVIRONMENT_DEFECT"
    DEPENDENCY_DEFECT = "DEPENDENCY_DEFECT"
    CONFIGURATION_DEFECT = "CONFIGURATION_DEFECT"
    FACTORY_TEMPLATE_DEFECT = "FACTORY_TEMPLATE_DEFECT"


class AmbiguityClass(str, Enum):
    BLOCKING = "BLOCKING"
    MATERIAL_ASSUMABLE = "MATERIAL_ASSUMABLE"
    IMPLEMENTATION_DETAIL = "IMPLEMENTATION_DETAIL"


class GateDecision(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
